[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[terminal]
osc52="OnlyCopy"

[window]
dynamic_padding = true
decorations = "Full"
title = "Alacritty"
opacity = 1
decorations_theme_variant = "Dark"
blur = true

[window.dimensions]
columns = 140
lines = 32

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12

# https://github.com/be5invis/Iosevka/releases/download/v34.8.0/PkgTTC-SGr-IosevkaTerm-34.8.0.zip
# Iosevka — Monospace, Default - Terminal TTC
[font.normal]
family = "Iosevka Term Medium"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.2

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[general]
live_config_reload = true
working_directory = "None"
